/* rygel-preferences-dialog.c generated by valac 0.22.0.18-aa6c, the Vala compiler
 * generated from rygel-preferences-dialog.vala, do not modify */

/*
 * Copyright (C) 2009 Nokia Corporation.
 * Copyright (C) 2012 Openismus GmbH.
 *
 * Author: Zeeshan Ali (Khattak) <zeeshanak@gnome.org>
 *                               <zeeshan.ali@nokia.com>
 *         Jens Georg <jensg@openismus.com>
 *
 * This file is part of Rygel.
 *
 * Rygel is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Rygel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <config.h>
#include <locale.h>
#include <glib/gi18n-lib.h>
#include <rygel-core.h>


#define RYGEL_TYPE_PREFERENCES_DIALOG (rygel_preferences_dialog_get_type ())
#define RYGEL_PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_PREFERENCES_DIALOG, RygelPreferencesDialog))
#define RYGEL_PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_PREFERENCES_DIALOG, RygelPreferencesDialogClass))
#define RYGEL_IS_PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_PREFERENCES_DIALOG))
#define RYGEL_IS_PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_PREFERENCES_DIALOG))
#define RYGEL_PREFERENCES_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_PREFERENCES_DIALOG, RygelPreferencesDialogClass))

typedef struct _RygelPreferencesDialog RygelPreferencesDialog;
typedef struct _RygelPreferencesDialogClass RygelPreferencesDialogClass;
typedef struct _RygelPreferencesDialogPrivate RygelPreferencesDialogPrivate;

#define RYGEL_TYPE_USER_CONFIG (rygel_user_config_get_type ())
#define RYGEL_USER_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_USER_CONFIG, RygelUserConfig))
#define RYGEL_USER_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_USER_CONFIG, RygelUserConfigClass))
#define RYGEL_IS_USER_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_USER_CONFIG))
#define RYGEL_IS_USER_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_USER_CONFIG))
#define RYGEL_USER_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_USER_CONFIG, RygelUserConfigClass))

typedef struct _RygelUserConfig RygelUserConfig;
typedef struct _RygelUserConfigClass RygelUserConfigClass;

#define RYGEL_TYPE_WRITABLE_USER_CONFIG (rygel_writable_user_config_get_type ())
#define RYGEL_WRITABLE_USER_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_WRITABLE_USER_CONFIG, RygelWritableUserConfig))
#define RYGEL_WRITABLE_USER_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_WRITABLE_USER_CONFIG, RygelWritableUserConfigClass))
#define RYGEL_IS_WRITABLE_USER_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_WRITABLE_USER_CONFIG))
#define RYGEL_IS_WRITABLE_USER_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_WRITABLE_USER_CONFIG))
#define RYGEL_WRITABLE_USER_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_WRITABLE_USER_CONFIG, RygelWritableUserConfigClass))

typedef struct _RygelWritableUserConfig RygelWritableUserConfig;
typedef struct _RygelWritableUserConfigClass RygelWritableUserConfigClass;

#define RYGEL_TYPE_PREFERENCES_SECTION (rygel_preferences_section_get_type ())
#define RYGEL_PREFERENCES_SECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_PREFERENCES_SECTION, RygelPreferencesSection))
#define RYGEL_PREFERENCES_SECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_PREFERENCES_SECTION, RygelPreferencesSectionClass))
#define RYGEL_IS_PREFERENCES_SECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_PREFERENCES_SECTION))
#define RYGEL_IS_PREFERENCES_SECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_PREFERENCES_SECTION))
#define RYGEL_PREFERENCES_SECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_PREFERENCES_SECTION, RygelPreferencesSectionClass))

typedef struct _RygelPreferencesSection RygelPreferencesSection;
typedef struct _RygelPreferencesSectionClass RygelPreferencesSectionClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define RYGEL_TYPE_NETWORK_PREF_SECTION (rygel_network_pref_section_get_type ())
#define RYGEL_NETWORK_PREF_SECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_NETWORK_PREF_SECTION, RygelNetworkPrefSection))
#define RYGEL_NETWORK_PREF_SECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_NETWORK_PREF_SECTION, RygelNetworkPrefSectionClass))
#define RYGEL_IS_NETWORK_PREF_SECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_NETWORK_PREF_SECTION))
#define RYGEL_IS_NETWORK_PREF_SECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_NETWORK_PREF_SECTION))
#define RYGEL_NETWORK_PREF_SECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_NETWORK_PREF_SECTION, RygelNetworkPrefSectionClass))

typedef struct _RygelNetworkPrefSection RygelNetworkPrefSection;
typedef struct _RygelNetworkPrefSectionClass RygelNetworkPrefSectionClass;

#define RYGEL_TYPE_MEDIA_PREF_SECTION (rygel_media_pref_section_get_type ())
#define RYGEL_MEDIA_PREF_SECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_PREF_SECTION, RygelMediaPrefSection))
#define RYGEL_MEDIA_PREF_SECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_PREF_SECTION, RygelMediaPrefSectionClass))
#define RYGEL_IS_MEDIA_PREF_SECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_PREF_SECTION))
#define RYGEL_IS_MEDIA_PREF_SECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_PREF_SECTION))
#define RYGEL_MEDIA_PREF_SECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_PREF_SECTION, RygelMediaPrefSectionClass))

typedef struct _RygelMediaPrefSection RygelMediaPrefSection;
typedef struct _RygelMediaPrefSectionClass RygelMediaPrefSectionClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _RygelPreferencesDialog {
	GObject parent_instance;
	RygelPreferencesDialogPrivate * priv;
};

struct _RygelPreferencesDialogClass {
	GObjectClass parent_class;
};

struct _RygelPreferencesDialogPrivate {
	RygelWritableUserConfig* config;
	GtkBuilder* builder;
	GtkDialog* dialog;
	GtkSwitch* upnp_check;
	GeeArrayList* sections;
};


static gpointer rygel_preferences_dialog_parent_class = NULL;

GType rygel_preferences_dialog_get_type (void) G_GNUC_CONST;
GType rygel_user_config_get_type (void) G_GNUC_CONST;
GType rygel_writable_user_config_get_type (void) G_GNUC_CONST;
GType rygel_preferences_section_get_type (void) G_GNUC_CONST;
#define RYGEL_PREFERENCES_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), RYGEL_TYPE_PREFERENCES_DIALOG, RygelPreferencesDialogPrivate))
enum  {
	RYGEL_PREFERENCES_DIALOG_DUMMY_PROPERTY
};
#define RYGEL_PREFERENCES_DIALOG_UI_FILE DATA_DIR "/rygel-preferences.ui"
#define RYGEL_PREFERENCES_DIALOG_DIALOG "preferences-dialog"
#define RYGEL_PREFERENCES_DIALOG_ICON SMALL_ICON_DIR "/rygel.png"
#define RYGEL_PREFERENCES_DIALOG_UPNP_CHECKBUTTON "upnp-checkbutton"
RygelPreferencesDialog* rygel_preferences_dialog_new (GError** error);
RygelPreferencesDialog* rygel_preferences_dialog_construct (GType object_type, GError** error);
RygelWritableUserConfig* rygel_writable_user_config_new (GError** error);
RygelWritableUserConfig* rygel_writable_user_config_construct (GType object_type, GError** error);
gboolean rygel_writable_user_config_is_upnp_enabled (RygelWritableUserConfig* self);
GType rygel_network_pref_section_get_type (void) G_GNUC_CONST;
RygelNetworkPrefSection* rygel_network_pref_section_new (GtkBuilder* builder, RygelWritableUserConfig* config, GError** error);
RygelNetworkPrefSection* rygel_network_pref_section_construct (GType object_type, GtkBuilder* builder, RygelWritableUserConfig* config, GError** error);
RygelMediaPrefSection* rygel_media_pref_section_new (GtkBuilder* builder, RygelWritableUserConfig* config);
RygelMediaPrefSection* rygel_media_pref_section_construct (GType object_type, GtkBuilder* builder, RygelWritableUserConfig* config);
GType rygel_media_pref_section_get_type (void) G_GNUC_CONST;
static void rygel_preferences_dialog_on_upnp_switch_toggled (RygelPreferencesDialog* self);
static void __lambda6_ (RygelPreferencesDialog* self);
static void ___lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
void rygel_preferences_dialog_run (RygelPreferencesDialog* self);
void rygel_writable_user_config_set_upnp_enabled (RygelWritableUserConfig* self, gboolean value);
void rygel_preferences_section_save (RygelPreferencesSection* self);
void rygel_writable_user_config_save (RygelWritableUserConfig* self);
gint rygel_preferences_dialog_main (gchar** args, int args_length1);
RygelUserConfig* rygel_user_config_get_default (GError** error);
void rygel_preferences_section_set_sensitivity (RygelPreferencesSection* self, gboolean sensitivity);
static void rygel_preferences_dialog_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	return self ? g_object_ref (self) : NULL;
#line 165 "rygel-preferences-dialog.c"
}


static void __lambda6_ (RygelPreferencesDialog* self) {
#line 62 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	rygel_preferences_dialog_on_upnp_switch_toggled (self);
#line 172 "rygel-preferences-dialog.c"
}


static void ___lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 61 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	__lambda6_ (self);
#line 179 "rygel-preferences-dialog.c"
}


RygelPreferencesDialog* rygel_preferences_dialog_construct (GType object_type, GError** error) {
	RygelPreferencesDialog * self = NULL;
	RygelWritableUserConfig* _tmp0_ = NULL;
	RygelWritableUserConfig* _tmp1_ = NULL;
	GtkBuilder* _tmp2_ = NULL;
	GtkBuilder* _tmp3_ = NULL;
	GtkBuilder* _tmp4_ = NULL;
	GObject* _tmp5_ = NULL;
	GtkDialog* _tmp6_ = NULL;
	GtkDialog* _tmp7_ = NULL;
	GtkBuilder* _tmp8_ = NULL;
	GObject* _tmp9_ = NULL;
	GtkSwitch* _tmp10_ = NULL;
	GtkSwitch* _tmp11_ = NULL;
	GtkDialog* _tmp12_ = NULL;
	GtkSwitch* _tmp13_ = NULL;
	RygelWritableUserConfig* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	GeeArrayList* _tmp16_ = NULL;
	RygelNetworkPrefSection* _tmp17_ = NULL;
	GtkBuilder* _tmp18_ = NULL;
	RygelWritableUserConfig* _tmp19_ = NULL;
	RygelNetworkPrefSection* _tmp20_ = NULL;
	GeeArrayList* _tmp21_ = NULL;
	RygelNetworkPrefSection* _tmp22_ = NULL;
	GeeArrayList* _tmp23_ = NULL;
	GtkBuilder* _tmp24_ = NULL;
	RygelWritableUserConfig* _tmp25_ = NULL;
	RygelMediaPrefSection* _tmp26_ = NULL;
	RygelMediaPrefSection* _tmp27_ = NULL;
	GtkSwitch* _tmp28_ = NULL;
	GError * _inner_error_ = NULL;
#line 40 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	self = (RygelPreferencesDialog*) g_object_new (object_type, NULL);
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp1_ = rygel_writable_user_config_new (&_inner_error_);
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp0_ = _tmp1_;
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	if (_inner_error_ != NULL) {
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		g_propagate_error (error, _inner_error_);
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_object_unref0 (self);
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		return NULL;
#line 229 "rygel-preferences-dialog.c"
	}
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->config);
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	self->priv->config = _tmp0_;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp2_ = gtk_builder_new ();
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->builder);
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	self->priv->builder = _tmp2_;
#line 44 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp3_ = self->priv->builder;
#line 44 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	gtk_builder_add_from_file (_tmp3_, RYGEL_PREFERENCES_DIALOG_UI_FILE, &_inner_error_);
#line 44 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	if (_inner_error_ != NULL) {
#line 44 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		g_propagate_error (error, _inner_error_);
#line 44 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_object_unref0 (self);
#line 44 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		return NULL;
#line 253 "rygel-preferences-dialog.c"
	}
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp4_ = self->priv->builder;
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp5_ = gtk_builder_get_object (_tmp4_, RYGEL_PREFERENCES_DIALOG_DIALOG);
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp6_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, GTK_TYPE_DIALOG, GtkDialog));
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->dialog);
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	self->priv->dialog = _tmp6_;
#line 47 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp7_ = self->priv->dialog;
#line 47 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_vala_assert (_tmp7_ != NULL, "this.dialog != null");
#line 48 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp8_ = self->priv->builder;
#line 48 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp9_ = gtk_builder_get_object (_tmp8_, RYGEL_PREFERENCES_DIALOG_UPNP_CHECKBUTTON);
#line 48 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp10_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, GTK_TYPE_SWITCH, GtkSwitch));
#line 48 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->upnp_check);
#line 48 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	self->priv->upnp_check = _tmp10_;
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp11_ = self->priv->upnp_check;
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_vala_assert (_tmp11_ != NULL, "this.upnp_check != null");
#line 51 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp12_ = self->priv->dialog;
#line 51 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	gtk_window_set_icon_from_file ((GtkWindow*) _tmp12_, RYGEL_PREFERENCES_DIALOG_ICON, &_inner_error_);
#line 51 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	if (_inner_error_ != NULL) {
#line 51 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		g_propagate_error (error, _inner_error_);
#line 51 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_object_unref0 (self);
#line 51 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		return NULL;
#line 295 "rygel-preferences-dialog.c"
	}
#line 53 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp13_ = self->priv->upnp_check;
#line 53 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp14_ = self->priv->config;
#line 53 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp15_ = rygel_writable_user_config_is_upnp_enabled (_tmp14_);
#line 53 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	gtk_switch_set_active (_tmp13_, _tmp15_);
#line 55 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp16_ = gee_array_list_new (RYGEL_TYPE_PREFERENCES_SECTION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 55 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->sections);
#line 55 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	self->priv->sections = _tmp16_;
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp18_ = self->priv->builder;
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp19_ = self->priv->config;
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp20_ = rygel_network_pref_section_new (_tmp18_, _tmp19_, &_inner_error_);
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp17_ = _tmp20_;
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	if (_inner_error_ != NULL) {
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		g_propagate_error (error, _inner_error_);
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_object_unref0 (self);
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		return NULL;
#line 327 "rygel-preferences-dialog.c"
	}
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp21_ = self->priv->sections;
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp22_ = _tmp17_;
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp21_, (RygelPreferencesSection*) _tmp22_);
#line 56 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (_tmp22_);
#line 57 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp23_ = self->priv->sections;
#line 57 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp24_ = self->priv->builder;
#line 57 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp25_ = self->priv->config;
#line 57 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp26_ = rygel_media_pref_section_new (_tmp24_, _tmp25_);
#line 57 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp27_ = _tmp26_;
#line 57 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp23_, (RygelPreferencesSection*) _tmp27_);
#line 57 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (_tmp27_);
#line 60 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	rygel_preferences_dialog_on_upnp_switch_toggled (self);
#line 61 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp28_ = self->priv->upnp_check;
#line 61 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	g_signal_connect_object ((GObject*) _tmp28_, "notify::active", (GCallback) ___lambda6__g_object_notify, self, 0);
#line 40 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	return self;
#line 359 "rygel-preferences-dialog.c"
}


RygelPreferencesDialog* rygel_preferences_dialog_new (GError** error) {
#line 40 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	return rygel_preferences_dialog_construct (RYGEL_TYPE_PREFERENCES_DIALOG, error);
#line 366 "rygel-preferences-dialog.c"
}


void rygel_preferences_dialog_run (RygelPreferencesDialog* self) {
	GtkDialog* _tmp0_ = NULL;
	GtkDialog* _tmp1_ = NULL;
	RygelWritableUserConfig* _tmp2_ = NULL;
	GtkSwitch* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	RygelWritableUserConfig* _tmp18_ = NULL;
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	g_return_if_fail (self != NULL);
#line 67 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp0_ = self->priv->dialog;
#line 67 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	gtk_dialog_run (_tmp0_);
#line 68 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp1_ = self->priv->dialog;
#line 68 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	gtk_widget_hide ((GtkWidget*) _tmp1_);
#line 70 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp2_ = self->priv->config;
#line 70 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp3_ = self->priv->upnp_check;
#line 70 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp4_ = gtk_switch_get_active (_tmp3_);
#line 70 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp5_ = _tmp4_;
#line 70 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	rygel_writable_user_config_set_upnp_enabled (_tmp2_, _tmp5_);
#line 398 "rygel-preferences-dialog.c"
	{
		GeeArrayList* _section_list = NULL;
		GeeArrayList* _tmp6_ = NULL;
		GeeArrayList* _tmp7_ = NULL;
		gint _section_size = 0;
		GeeArrayList* _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		gint _section_index = 0;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp6_ = self->priv->sections;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp7_ = _g_object_ref0 (_tmp6_);
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_section_list = _tmp7_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp8_ = _section_list;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp9_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp8_);
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp10_ = _tmp9_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_section_size = _tmp10_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_section_index = -1;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		while (TRUE) {
#line 426 "rygel-preferences-dialog.c"
			gint _tmp11_ = 0;
			gint _tmp12_ = 0;
			gint _tmp13_ = 0;
			RygelPreferencesSection* section = NULL;
			GeeArrayList* _tmp14_ = NULL;
			gint _tmp15_ = 0;
			gpointer _tmp16_ = NULL;
			RygelPreferencesSection* _tmp17_ = NULL;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp11_ = _section_index;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_section_index = _tmp11_ + 1;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp12_ = _section_index;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp13_ = _section_size;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			if (!(_tmp12_ < _tmp13_)) {
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
				break;
#line 447 "rygel-preferences-dialog.c"
			}
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp14_ = _section_list;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp15_ = _section_index;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp16_ = gee_abstract_list_get ((GeeAbstractList*) _tmp14_, _tmp15_);
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			section = (RygelPreferencesSection*) _tmp16_;
#line 72 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp17_ = section;
#line 72 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			rygel_preferences_section_save (_tmp17_);
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_g_object_unref0 (section);
#line 463 "rygel-preferences-dialog.c"
		}
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_object_unref0 (_section_list);
#line 467 "rygel-preferences-dialog.c"
	}
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_tmp18_ = self->priv->config;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	rygel_writable_user_config_save (_tmp18_);
#line 473 "rygel-preferences-dialog.c"
}


gint rygel_preferences_dialog_main (gchar** args, int args_length1) {
	gint result = 0;
	GError * _inner_error_ = NULL;
#line 79 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	setlocale (LC_ALL, "");
#line 80 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
#line 82 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
#line 83 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	textdomain (GETTEXT_PACKAGE);
#line 85 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	gtk_init (&args_length1, &args);
#line 490 "rygel-preferences-dialog.c"
	{
		RygelUserConfig* _tmp0_ = NULL;
		RygelUserConfig* _tmp1_ = NULL;
		RygelUserConfig* _tmp2_ = NULL;
		RygelPreferencesDialog* dialog = NULL;
		RygelPreferencesDialog* _tmp3_ = NULL;
		RygelPreferencesDialog* _tmp4_ = NULL;
#line 88 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp1_ = rygel_user_config_get_default (&_inner_error_);
#line 88 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp0_ = _tmp1_;
#line 88 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		if (_inner_error_ != NULL) {
#line 504 "rygel-preferences-dialog.c"
			goto __catch0_g_error;
		}
#line 88 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp2_ = _tmp0_;
#line 88 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		rygel_meta_config_register_configuration ((RygelConfiguration*) _tmp2_);
#line 88 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_object_unref0 (_tmp2_);
#line 89 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp3_ = rygel_preferences_dialog_new (&_inner_error_);
#line 89 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		dialog = _tmp3_;
#line 89 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		if (_inner_error_ != NULL) {
#line 519 "rygel-preferences-dialog.c"
			goto __catch0_g_error;
		}
#line 91 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp4_ = dialog;
#line 91 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		rygel_preferences_dialog_run (_tmp4_);
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_object_unref0 (dialog);
#line 528 "rygel-preferences-dialog.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* err = NULL;
		const gchar* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		err = _inner_error_;
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_inner_error_ = NULL;
#line 93 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp5_ = _ ("Failed to create preferences dialog: %s");
#line 93 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp6_ = err->message;
#line 93 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		g_error (_tmp5_, _tmp6_);
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_error_free0 (err);
#line 548 "rygel-preferences-dialog.c"
	}
	__finally0:
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	if (_inner_error_ != NULL) {
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		g_clear_error (&_inner_error_);
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		return 0;
#line 559 "rygel-preferences-dialog.c"
	}
#line 96 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	result = 0;
#line 96 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	return result;
#line 565 "rygel-preferences-dialog.c"
}


int main (int argc, char ** argv) {
#line 78 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	g_type_init ();
#line 78 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	return rygel_preferences_dialog_main (argv, argc);
#line 574 "rygel-preferences-dialog.c"
}


static void rygel_preferences_dialog_on_upnp_switch_toggled (RygelPreferencesDialog* self) {
#line 99 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	g_return_if_fail (self != NULL);
#line 581 "rygel-preferences-dialog.c"
	{
		GeeArrayList* _section_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _section_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _section_index = 0;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp0_ = self->priv->sections;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp1_ = _g_object_ref0 (_tmp0_);
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_section_list = _tmp1_;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp2_ = _section_list;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_tmp4_ = _tmp3_;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_section_size = _tmp4_;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_section_index = -1;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		while (TRUE) {
#line 609 "rygel-preferences-dialog.c"
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			RygelPreferencesSection* section = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			RygelPreferencesSection* _tmp11_ = NULL;
			GtkSwitch* _tmp12_ = NULL;
			gboolean _tmp13_ = FALSE;
			gboolean _tmp14_ = FALSE;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp5_ = _section_index;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_section_index = _tmp5_ + 1;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp6_ = _section_index;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp7_ = _section_size;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			if (!(_tmp6_ < _tmp7_)) {
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
				break;
#line 633 "rygel-preferences-dialog.c"
			}
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp8_ = _section_list;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp9_ = _section_index;
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			section = (RygelPreferencesSection*) _tmp10_;
#line 101 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp11_ = section;
#line 101 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp12_ = self->priv->upnp_check;
#line 101 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp13_ = gtk_switch_get_active (_tmp12_);
#line 101 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_tmp14_ = _tmp13_;
#line 101 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			rygel_preferences_section_set_sensitivity (_tmp11_, _tmp14_);
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
			_g_object_unref0 (section);
#line 655 "rygel-preferences-dialog.c"
		}
#line 100 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
		_g_object_unref0 (_section_list);
#line 659 "rygel-preferences-dialog.c"
	}
}


static void rygel_preferences_dialog_class_init (RygelPreferencesDialogClass * klass) {
#line 28 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	rygel_preferences_dialog_parent_class = g_type_class_peek_parent (klass);
#line 28 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	g_type_class_add_private (klass, sizeof (RygelPreferencesDialogPrivate));
#line 28 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	G_OBJECT_CLASS (klass)->finalize = rygel_preferences_dialog_finalize;
#line 671 "rygel-preferences-dialog.c"
}


static void rygel_preferences_dialog_instance_init (RygelPreferencesDialog * self) {
#line 28 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	self->priv = RYGEL_PREFERENCES_DIALOG_GET_PRIVATE (self);
#line 678 "rygel-preferences-dialog.c"
}


static void rygel_preferences_dialog_finalize (GObject* obj) {
	RygelPreferencesDialog * self;
#line 28 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, RYGEL_TYPE_PREFERENCES_DIALOG, RygelPreferencesDialog);
#line 34 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->config);
#line 35 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->builder);
#line 36 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->dialog);
#line 37 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->upnp_check);
#line 38 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	_g_object_unref0 (self->priv->sections);
#line 28 "/home/jku/src/jhbuild/sources/rygel/src/ui/rygel-preferences-dialog.vala"
	G_OBJECT_CLASS (rygel_preferences_dialog_parent_class)->finalize (obj);
#line 698 "rygel-preferences-dialog.c"
}


GType rygel_preferences_dialog_get_type (void) {
	static volatile gsize rygel_preferences_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&rygel_preferences_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RygelPreferencesDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rygel_preferences_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RygelPreferencesDialog), 0, (GInstanceInitFunc) rygel_preferences_dialog_instance_init, NULL };
		GType rygel_preferences_dialog_type_id;
		rygel_preferences_dialog_type_id = g_type_register_static (G_TYPE_OBJECT, "RygelPreferencesDialog", &g_define_type_info, 0);
		g_once_init_leave (&rygel_preferences_dialog_type_id__volatile, rygel_preferences_dialog_type_id);
	}
	return rygel_preferences_dialog_type_id__volatile;
}



