/* rygel-media-export-writable-db-container.c generated by valac 0.16.1, the Vala compiler
 * generated from rygel-media-export-writable-db-container.vala, do not modify */

/*
 * Copyright (C) 2010 Jens Georg <mail@jensge.org>.
 *
 * Author: Jens Georg <mail@jensge.org>
 *
 * This file is part of Rygel.
 *
 * Rygel is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Rygel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <rygel-server.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define RYGEL_MEDIA_EXPORT_TYPE_DB_CONTAINER (rygel_media_export_db_container_get_type ())
#define RYGEL_MEDIA_EXPORT_DB_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_MEDIA_EXPORT_TYPE_DB_CONTAINER, RygelMediaExportDBContainer))
#define RYGEL_MEDIA_EXPORT_DB_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_MEDIA_EXPORT_TYPE_DB_CONTAINER, RygelMediaExportDBContainerClass))
#define RYGEL_MEDIA_EXPORT_IS_DB_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_MEDIA_EXPORT_TYPE_DB_CONTAINER))
#define RYGEL_MEDIA_EXPORT_IS_DB_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_MEDIA_EXPORT_TYPE_DB_CONTAINER))
#define RYGEL_MEDIA_EXPORT_DB_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_MEDIA_EXPORT_TYPE_DB_CONTAINER, RygelMediaExportDBContainerClass))

typedef struct _RygelMediaExportDBContainer RygelMediaExportDBContainer;
typedef struct _RygelMediaExportDBContainerClass RygelMediaExportDBContainerClass;
typedef struct _RygelMediaExportDBContainerPrivate RygelMediaExportDBContainerPrivate;

#define RYGEL_MEDIA_EXPORT_TYPE_MEDIA_CACHE (rygel_media_export_media_cache_get_type ())
#define RYGEL_MEDIA_EXPORT_MEDIA_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_MEDIA_EXPORT_TYPE_MEDIA_CACHE, RygelMediaExportMediaCache))
#define RYGEL_MEDIA_EXPORT_MEDIA_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_MEDIA_EXPORT_TYPE_MEDIA_CACHE, RygelMediaExportMediaCacheClass))
#define RYGEL_MEDIA_EXPORT_IS_MEDIA_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_MEDIA_EXPORT_TYPE_MEDIA_CACHE))
#define RYGEL_MEDIA_EXPORT_IS_MEDIA_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_MEDIA_EXPORT_TYPE_MEDIA_CACHE))
#define RYGEL_MEDIA_EXPORT_MEDIA_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_MEDIA_EXPORT_TYPE_MEDIA_CACHE, RygelMediaExportMediaCacheClass))

typedef struct _RygelMediaExportMediaCache RygelMediaExportMediaCache;
typedef struct _RygelMediaExportMediaCacheClass RygelMediaExportMediaCacheClass;

#define RYGEL_MEDIA_EXPORT_TYPE_WRITABLE_DB_CONTAINER (rygel_media_export_writable_db_container_get_type ())
#define RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_MEDIA_EXPORT_TYPE_WRITABLE_DB_CONTAINER, RygelMediaExportWritableDbContainer))
#define RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_MEDIA_EXPORT_TYPE_WRITABLE_DB_CONTAINER, RygelMediaExportWritableDbContainerClass))
#define RYGEL_MEDIA_EXPORT_IS_WRITABLE_DB_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_MEDIA_EXPORT_TYPE_WRITABLE_DB_CONTAINER))
#define RYGEL_MEDIA_EXPORT_IS_WRITABLE_DB_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_MEDIA_EXPORT_TYPE_WRITABLE_DB_CONTAINER))
#define RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_MEDIA_EXPORT_TYPE_WRITABLE_DB_CONTAINER, RygelMediaExportWritableDbContainerClass))

typedef struct _RygelMediaExportWritableDbContainer RygelMediaExportWritableDbContainer;
typedef struct _RygelMediaExportWritableDbContainerClass RygelMediaExportWritableDbContainerClass;
typedef struct _RygelMediaExportWritableDbContainerPrivate RygelMediaExportWritableDbContainerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _RygelMediaExportWritableDbContainerAddItemData RygelMediaExportWritableDbContainerAddItemData;
typedef struct _RygelMediaExportWritableDbContainerRemoveItemData RygelMediaExportWritableDbContainerRemoveItemData;

struct _RygelMediaExportDBContainer {
	RygelMediaContainer parent_instance;
	RygelMediaExportDBContainerPrivate * priv;
	RygelMediaExportMediaCache* media_db;
};

struct _RygelMediaExportDBContainerClass {
	RygelMediaContainerClass parent_class;
	void (*search) (RygelMediaExportDBContainer* self, RygelSearchExpression* expression, guint offset, guint max_count, const gchar* sort_criteria, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
	RygelMediaObjects* (*search_finish) (RygelMediaExportDBContainer* self, GAsyncResult* _res_, guint* total_matches, GError** error);
};

struct _RygelMediaExportWritableDbContainer {
	RygelMediaExportDBContainer parent_instance;
	RygelMediaExportWritableDbContainerPrivate * priv;
};

struct _RygelMediaExportWritableDbContainerClass {
	RygelMediaExportDBContainerClass parent_class;
};

struct _RygelMediaExportWritableDbContainerPrivate {
	GeeArrayList* _create_classes;
};

struct _RygelMediaExportWritableDbContainerAddItemData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	RygelMediaExportWritableDbContainer* self;
	RygelMediaItem* item;
	GCancellable* cancellable;
	RygelMediaItem* _tmp0_;
	RygelMediaItem* _tmp1_;
	GeeArrayList* _tmp2_;
	gpointer _tmp3_;
	gchar* _tmp4_;
	GFile* _tmp5_;
	GFile* _tmp6_;
	GFile* file;
	GFile* _tmp7_;
	gboolean _tmp8_;
	RygelMediaItem* _tmp9_;
	gint64 _tmp10_;
	RygelMediaItem* _tmp11_;
	GFile* _tmp12_;
	gchar* _tmp13_;
	RygelMediaExportMediaCache* _tmp14_;
	RygelMediaItem* _tmp15_;
	GError * _inner_error_;
};

typedef enum  {
	RYGEL_MEDIA_EXPORT_DATABASE_ERROR_IO_ERROR,
	RYGEL_MEDIA_EXPORT_DATABASE_ERROR_SQLITE_ERROR
} RygelMediaExportDatabaseError;
#define RYGEL_MEDIA_EXPORT_DATABASE_ERROR rygel_media_export_database_error_quark ()
struct _RygelMediaExportWritableDbContainerRemoveItemData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	RygelMediaExportWritableDbContainer* self;
	gchar* id;
	GCancellable* cancellable;
	RygelMediaExportMediaCache* _tmp0_;
	const gchar* _tmp1_;
	GError * _inner_error_;
};


static gpointer rygel_media_export_writable_db_container_parent_class = NULL;
static RygelWritableContainerIface* rygel_media_export_writable_db_container_rygel_writable_container_parent_iface = NULL;

GType rygel_media_export_db_container_get_type (void) G_GNUC_CONST;
GType rygel_media_export_media_cache_get_type (void) G_GNUC_CONST;
GType rygel_media_export_writable_db_container_get_type (void) G_GNUC_CONST;
#define RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), RYGEL_MEDIA_EXPORT_TYPE_WRITABLE_DB_CONTAINER, RygelMediaExportWritableDbContainerPrivate))
enum  {
	RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_DUMMY_PROPERTY,
	RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_CREATE_CLASSES
};
RygelMediaExportWritableDbContainer* rygel_media_export_writable_db_container_new (RygelMediaExportMediaCache* media_db, const gchar* id, const gchar* title);
RygelMediaExportWritableDbContainer* rygel_media_export_writable_db_container_construct (GType object_type, RygelMediaExportMediaCache* media_db, const gchar* id, const gchar* title);
RygelMediaExportDBContainer* rygel_media_export_db_container_new (RygelMediaExportMediaCache* media_db, const gchar* id, const gchar* title);
RygelMediaExportDBContainer* rygel_media_export_db_container_construct (GType object_type, RygelMediaExportMediaCache* media_db, const gchar* id, const gchar* title);
static void rygel_media_export_writable_db_container_real_add_item_data_free (gpointer _data);
static void rygel_media_export_writable_db_container_real_add_item (RygelWritableContainer* base, RygelMediaItem* item, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean rygel_media_export_writable_db_container_real_add_item_co (RygelMediaExportWritableDbContainerAddItemData* _data_);
gchar* rygel_media_export_media_cache_get_id (GFile* file);
void rygel_media_export_media_cache_save_item (RygelMediaExportMediaCache* self, RygelMediaItem* item, GError** error);
static void rygel_media_export_writable_db_container_real_remove_item_data_free (gpointer _data);
static void rygel_media_export_writable_db_container_real_remove_item (RygelWritableContainer* base, const gchar* id, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean rygel_media_export_writable_db_container_real_remove_item_co (RygelMediaExportWritableDbContainerRemoveItemData* _data_);
GQuark rygel_media_export_database_error_quark (void);
void rygel_media_export_media_cache_remove_by_id (RygelMediaExportMediaCache* self, const gchar* id, GError** error);
static void rygel_media_export_writable_db_container_finalize (GObject* obj);
static void _vala_rygel_media_export_writable_db_container_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_rygel_media_export_writable_db_container_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


RygelMediaExportWritableDbContainer* rygel_media_export_writable_db_container_construct (GType object_type, RygelMediaExportMediaCache* media_db, const gchar* id, const gchar* title) {
	RygelMediaExportWritableDbContainer * self = NULL;
	RygelMediaExportMediaCache* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	GeeArrayList* _tmp3_;
	GeeArrayList* _tmp4_;
	GeeArrayList* _tmp5_;
	GeeArrayList* _tmp6_;
	GeeArrayList* _tmp7_;
	GeeArrayList* _tmp8_;
	GeeArrayList* _tmp9_;
	GeeArrayList* _tmp10_;
	GeeArrayList* _tmp11_;
	GeeArrayList* _tmp12_;
	GeeArrayList* _tmp13_;
	GeeArrayList* _tmp14_;
#line 28 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_return_val_if_fail (media_db != NULL, NULL);
#line 28 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_return_val_if_fail (id != NULL, NULL);
#line 28 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_return_val_if_fail (title != NULL, NULL);
#line 29 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp0_ = media_db;
#line 29 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp1_ = id;
#line 29 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp2_ = title;
#line 29 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	self = (RygelMediaExportWritableDbContainer*) rygel_media_export_db_container_construct (object_type, _tmp0_, _tmp1_, _tmp2_);
#line 31 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp3_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL);
#line 31 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp4_ = _tmp3_;
#line 31 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	rygel_writable_container_set_create_classes ((RygelWritableContainer*) self, _tmp4_);
#line 31 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (_tmp4_);
#line 32 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp5_ = rygel_writable_container_get_create_classes ((RygelWritableContainer*) self);
#line 32 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp6_ = _tmp5_;
#line 32 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, RYGEL_IMAGE_ITEM_UPNP_CLASS);
#line 33 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp7_ = rygel_writable_container_get_create_classes ((RygelWritableContainer*) self);
#line 33 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp8_ = _tmp7_;
#line 33 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp8_, RYGEL_PHOTO_ITEM_UPNP_CLASS);
#line 34 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp9_ = rygel_writable_container_get_create_classes ((RygelWritableContainer*) self);
#line 34 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp10_ = _tmp9_;
#line 34 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp10_, RYGEL_VIDEO_ITEM_UPNP_CLASS);
#line 35 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp11_ = rygel_writable_container_get_create_classes ((RygelWritableContainer*) self);
#line 35 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp12_ = _tmp11_;
#line 35 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp12_, RYGEL_AUDIO_ITEM_UPNP_CLASS);
#line 36 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp13_ = rygel_writable_container_get_create_classes ((RygelWritableContainer*) self);
#line 36 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp14_ = _tmp13_;
#line 36 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp14_, RYGEL_MUSIC_ITEM_UPNP_CLASS);
#line 28 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	return self;
#line 245 "rygel-media-export-writable-db-container.c"
}


RygelMediaExportWritableDbContainer* rygel_media_export_writable_db_container_new (RygelMediaExportMediaCache* media_db, const gchar* id, const gchar* title) {
#line 28 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	return rygel_media_export_writable_db_container_construct (RYGEL_MEDIA_EXPORT_TYPE_WRITABLE_DB_CONTAINER, media_db, id, title);
#line 252 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_real_add_item_data_free (gpointer _data) {
	RygelMediaExportWritableDbContainerAddItemData* _data_;
	_data_ = _data;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (_data_->item);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (_data_->cancellable);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (_data_->self);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_slice_free (RygelMediaExportWritableDbContainerAddItemData, _data_);
#line 267 "rygel-media-export-writable-db-container.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	return self ? g_object_ref (self) : NULL;
#line 274 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_real_add_item (RygelWritableContainer* base, RygelMediaItem* item, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	RygelMediaExportWritableDbContainer * self;
	RygelMediaExportWritableDbContainerAddItemData* _data_;
	RygelMediaExportWritableDbContainer* _tmp0_;
	RygelMediaItem* _tmp1_;
	RygelMediaItem* _tmp2_;
	GCancellable* _tmp3_;
	GCancellable* _tmp4_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	self = (RygelMediaExportWritableDbContainer*) base;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_ = g_slice_new0 (RygelMediaExportWritableDbContainerAddItemData);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, rygel_media_export_writable_db_container_real_add_item);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, rygel_media_export_writable_db_container_real_add_item_data_free);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->self = _tmp0_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp1_ = item;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->item = _tmp2_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp3_ = cancellable;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->cancellable = _tmp4_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	rygel_media_export_writable_db_container_real_add_item_co (_data_);
#line 312 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_real_add_item_finish (RygelWritableContainer* base, GAsyncResult* _res_, GError** error) {
	RygelMediaExportWritableDbContainerAddItemData* _data_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	if (g_simple_async_result_propagate_error (G_SIMPLE_ASYNC_RESULT (_res_), error)) {
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		return;
#line 322 "rygel-media-export-writable-db-container.c"
	}
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 326 "rygel-media-export-writable-db-container.c"
}


static gboolean rygel_media_export_writable_db_container_real_add_item_co (RygelMediaExportWritableDbContainerAddItemData* _data_) {
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	switch (_data_->_state_) {
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		case 0:
#line 335 "rygel-media-export-writable-db-container.c"
		goto _state_0;
		default:
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_assert_not_reached ();
#line 340 "rygel-media-export-writable-db-container.c"
	}
	_state_0:
#line 41 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp0_ = _data_->item;
#line 41 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	((RygelMediaObject*) _data_->_tmp0_)->parent = (RygelMediaContainer*) _data_->self;
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp1_ = _data_->item;
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp2_ = ((RygelMediaObject*) _data_->_tmp1_)->uris;
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp3_ = NULL;
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp3_ = gee_abstract_list_get ((GeeAbstractList*) _data_->_tmp2_, 0);
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp4_ = (gchar*) _data_->_tmp3_;
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp5_ = NULL;
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp5_ = g_file_new_for_uri (_data_->_tmp4_);
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp6_ = _data_->_tmp5_;
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_free0 (_data_->_tmp4_);
#line 42 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->file = _data_->_tmp6_;
#line 44 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp7_ = _data_->file;
#line 44 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp8_ = FALSE;
#line 44 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp8_ = g_file_is_native (_data_->_tmp7_);
#line 44 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	if (_data_->_tmp8_) {
#line 45 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		_data_->_tmp9_ = _data_->item;
#line 45 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		_data_->_tmp10_ = G_MAXINT64;
#line 45 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		((RygelMediaObject*) _data_->_tmp9_)->modified = (guint64) _data_->_tmp10_;
#line 381 "rygel-media-export-writable-db-container.c"
	}
#line 47 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp11_ = _data_->item;
#line 47 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp12_ = _data_->file;
#line 47 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp13_ = NULL;
#line 47 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp13_ = rygel_media_export_media_cache_get_id (_data_->_tmp12_);
#line 47 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_free0 (((RygelMediaObject*) _data_->_tmp11_)->id);
#line 47 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	((RygelMediaObject*) _data_->_tmp11_)->id = _data_->_tmp13_;
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp14_ = ((RygelMediaExportDBContainer*) _data_->self)->media_db;
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp15_ = _data_->item;
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	rygel_media_export_media_cache_save_item (_data_->_tmp14_, _data_->_tmp15_, &_data_->_inner_error_);
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	if (_data_->_inner_error_ != NULL) {
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_error_free (_data_->_inner_error_);
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		_g_object_unref0 (_data_->file);
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		if (_data_->_state_ == 0) {
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
			g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 413 "rygel-media-export-writable-db-container.c"
		} else {
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
			g_simple_async_result_complete (_data_->_async_result);
#line 417 "rygel-media-export-writable-db-container.c"
		}
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_object_unref (_data_->_async_result);
#line 48 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		return FALSE;
#line 423 "rygel-media-export-writable-db-container.c"
	}
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (_data_->file);
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	if (_data_->_state_ == 0) {
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 431 "rygel-media-export-writable-db-container.c"
	} else {
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 435 "rygel-media-export-writable-db-container.c"
	}
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_object_unref (_data_->_async_result);
#line 39 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	return FALSE;
#line 441 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_real_remove_item_data_free (gpointer _data) {
	RygelMediaExportWritableDbContainerRemoveItemData* _data_;
	_data_ = _data;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_free0 (_data_->id);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (_data_->cancellable);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (_data_->self);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_slice_free (RygelMediaExportWritableDbContainerRemoveItemData, _data_);
#line 456 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_real_remove_item (RygelWritableContainer* base, const gchar* id, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	RygelMediaExportWritableDbContainer * self;
	RygelMediaExportWritableDbContainerRemoveItemData* _data_;
	RygelMediaExportWritableDbContainer* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	GCancellable* _tmp3_;
	GCancellable* _tmp4_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	self = (RygelMediaExportWritableDbContainer*) base;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_ = g_slice_new0 (RygelMediaExportWritableDbContainerRemoveItemData);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, rygel_media_export_writable_db_container_real_remove_item);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, rygel_media_export_writable_db_container_real_remove_item_data_free);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->self = _tmp0_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp1_ = id;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->id = _tmp2_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp3_ = cancellable;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->cancellable = _tmp4_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	rygel_media_export_writable_db_container_real_remove_item_co (_data_);
#line 494 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_real_remove_item_finish (RygelWritableContainer* base, GAsyncResult* _res_, GError** error) {
	RygelMediaExportWritableDbContainerRemoveItemData* _data_;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	if (g_simple_async_result_propagate_error (G_SIMPLE_ASYNC_RESULT (_res_), error)) {
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		return;
#line 504 "rygel-media-export-writable-db-container.c"
	}
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 508 "rygel-media-export-writable-db-container.c"
}


static gboolean rygel_media_export_writable_db_container_real_remove_item_co (RygelMediaExportWritableDbContainerRemoveItemData* _data_) {
#line 51 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	switch (_data_->_state_) {
#line 51 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		case 0:
#line 517 "rygel-media-export-writable-db-container.c"
		goto _state_0;
		default:
#line 51 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_assert_not_reached ();
#line 522 "rygel-media-export-writable-db-container.c"
	}
	_state_0:
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp0_ = ((RygelMediaExportDBContainer*) _data_->self)->media_db;
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_data_->_tmp1_ = _data_->id;
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	rygel_media_export_media_cache_remove_by_id (_data_->_tmp0_, _data_->_tmp1_, &_data_->_inner_error_);
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	if (_data_->_inner_error_ != NULL) {
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_error_free (_data_->_inner_error_);
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		if (_data_->_state_ == 0) {
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
			g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 541 "rygel-media-export-writable-db-container.c"
		} else {
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
			g_simple_async_result_complete (_data_->_async_result);
#line 545 "rygel-media-export-writable-db-container.c"
		}
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_object_unref (_data_->_async_result);
#line 53 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		return FALSE;
#line 551 "rygel-media-export-writable-db-container.c"
	}
#line 51 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	if (_data_->_state_ == 0) {
#line 51 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 557 "rygel-media-export-writable-db-container.c"
	} else {
#line 51 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 561 "rygel-media-export-writable-db-container.c"
	}
#line 51 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_object_unref (_data_->_async_result);
#line 51 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	return FALSE;
#line 567 "rygel-media-export-writable-db-container.c"
}


static GeeArrayList* rygel_media_export_writable_db_container_real_get_create_classes (RygelWritableContainer* base) {
	GeeArrayList* result;
	RygelMediaExportWritableDbContainer* self;
	GeeArrayList* _tmp0_;
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	self = (RygelMediaExportWritableDbContainer*) base;
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp0_ = self->priv->_create_classes;
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	result = _tmp0_;
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	return result;
#line 583 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_real_set_create_classes (RygelWritableContainer* base, GeeArrayList* value) {
	RygelMediaExportWritableDbContainer* self;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	self = (RygelMediaExportWritableDbContainer*) base;
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp0_ = value;
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (self->priv->_create_classes);
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	self->priv->_create_classes = _tmp1_;
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_object_notify ((GObject *) self, "create-classes");
#line 603 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_class_init (RygelMediaExportWritableDbContainerClass * klass) {
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	rygel_media_export_writable_db_container_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_type_class_add_private (klass, sizeof (RygelMediaExportWritableDbContainerPrivate));
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_rygel_media_export_writable_db_container_get_property;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_rygel_media_export_writable_db_container_set_property;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	G_OBJECT_CLASS (klass)->finalize = rygel_media_export_writable_db_container_finalize;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_CREATE_CLASSES, g_param_spec_object ("create-classes", "create-classes", "create-classes", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 620 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_rygel_writable_container_interface_init (RygelWritableContainerIface * iface) {
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	rygel_media_export_writable_db_container_rygel_writable_container_parent_iface = g_type_interface_peek_parent (iface);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	iface->add_item = (void (*)(RygelWritableContainer*, RygelMediaItem*, GCancellable*, GError**)) rygel_media_export_writable_db_container_real_add_item;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	iface->add_item_finish = rygel_media_export_writable_db_container_real_add_item_finish;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	iface->remove_item = (void (*)(RygelWritableContainer*, const gchar*, GCancellable*, GError**)) rygel_media_export_writable_db_container_real_remove_item;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	iface->remove_item_finish = rygel_media_export_writable_db_container_real_remove_item_finish;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	iface->get_create_classes = rygel_media_export_writable_db_container_real_get_create_classes;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	iface->set_create_classes = rygel_media_export_writable_db_container_real_set_create_classes;
#line 639 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_instance_init (RygelMediaExportWritableDbContainer * self) {
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	self->priv = RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_GET_PRIVATE (self);
#line 646 "rygel-media-export-writable-db-container.c"
}


static void rygel_media_export_writable_db_container_finalize (GObject* obj) {
	RygelMediaExportWritableDbContainer * self;
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	self = RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER (obj);
#line 26 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	_g_object_unref0 (self->priv->_create_classes);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	G_OBJECT_CLASS (rygel_media_export_writable_db_container_parent_class)->finalize (obj);
#line 658 "rygel-media-export-writable-db-container.c"
}


GType rygel_media_export_writable_db_container_get_type (void) {
	static volatile gsize rygel_media_export_writable_db_container_type_id__volatile = 0;
	if (g_once_init_enter (&rygel_media_export_writable_db_container_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RygelMediaExportWritableDbContainerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rygel_media_export_writable_db_container_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RygelMediaExportWritableDbContainer), 0, (GInstanceInitFunc) rygel_media_export_writable_db_container_instance_init, NULL };
		static const GInterfaceInfo rygel_writable_container_info = { (GInterfaceInitFunc) rygel_media_export_writable_db_container_rygel_writable_container_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType rygel_media_export_writable_db_container_type_id;
		rygel_media_export_writable_db_container_type_id = g_type_register_static (RYGEL_MEDIA_EXPORT_TYPE_DB_CONTAINER, "RygelMediaExportWritableDbContainer", &g_define_type_info, 0);
		g_type_add_interface_static (rygel_media_export_writable_db_container_type_id, RYGEL_TYPE_WRITABLE_CONTAINER, &rygel_writable_container_info);
		g_once_init_leave (&rygel_media_export_writable_db_container_type_id__volatile, rygel_media_export_writable_db_container_type_id);
	}
	return rygel_media_export_writable_db_container_type_id__volatile;
}


static void _vala_rygel_media_export_writable_db_container_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	RygelMediaExportWritableDbContainer * self;
	self = RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER (object);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	switch (property_id) {
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		case RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_CREATE_CLASSES:
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		g_value_set_object (value, rygel_writable_container_get_create_classes ((RygelWritableContainer*) self));
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		break;
#line 687 "rygel-media-export-writable-db-container.c"
		default:
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		break;
#line 693 "rygel-media-export-writable-db-container.c"
	}
}


static void _vala_rygel_media_export_writable_db_container_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	RygelMediaExportWritableDbContainer * self;
	self = RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER (object);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
	switch (property_id) {
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		case RYGEL_MEDIA_EXPORT_WRITABLE_DB_CONTAINER_CREATE_CLASSES:
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		rygel_writable_container_set_create_classes ((RygelWritableContainer*) self, g_value_get_object (value));
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		break;
#line 709 "rygel-media-export-writable-db-container.c"
		default:
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/mryan/src/rygel/src/plugins/media-export/rygel-media-export-writable-db-container.vala"
		break;
#line 715 "rygel-media-export-writable-db-container.c"
	}
}



