/* rygel-http-byte-seek.c generated by valac 0.22.0.18-aa6c, the Vala compiler
 * generated from rygel-http-byte-seek.vala, do not modify */

/*
 * Copyright (C) 2009 Nokia Corporation.
 * Copyright (C) 2012 Intel Corporation.
 *
 * Author: Zeeshan Ali (Khattak) <zeeshanak@gnome.org>
 *                               <zeeshan.ali@nokia.com>
 *         Jens Georg <jensg@openismus.com>
 *
 * This file is part of Rygel.
 *
 * Rygel is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Rygel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <libsoup/soup.h>
#include <stdlib.h>
#include <string.h>
#include <rygel-core.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>


#define RYGEL_TYPE_HTTP_SEEK (rygel_http_seek_get_type ())
#define RYGEL_HTTP_SEEK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_SEEK, RygelHTTPSeek))
#define RYGEL_HTTP_SEEK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_SEEK, RygelHTTPSeekClass))
#define RYGEL_IS_HTTP_SEEK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_SEEK))
#define RYGEL_IS_HTTP_SEEK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_SEEK))
#define RYGEL_HTTP_SEEK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_SEEK, RygelHTTPSeekClass))

typedef struct _RygelHTTPSeek RygelHTTPSeek;
typedef struct _RygelHTTPSeekClass RygelHTTPSeekClass;
typedef struct _RygelHTTPSeekPrivate RygelHTTPSeekPrivate;

#define RYGEL_TYPE_HTTP_BYTE_SEEK (rygel_http_byte_seek_get_type ())
#define RYGEL_HTTP_BYTE_SEEK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_BYTE_SEEK, RygelHTTPByteSeek))
#define RYGEL_HTTP_BYTE_SEEK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_BYTE_SEEK, RygelHTTPByteSeekClass))
#define RYGEL_IS_HTTP_BYTE_SEEK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_BYTE_SEEK))
#define RYGEL_IS_HTTP_BYTE_SEEK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_BYTE_SEEK))
#define RYGEL_HTTP_BYTE_SEEK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_BYTE_SEEK, RygelHTTPByteSeekClass))

typedef struct _RygelHTTPByteSeek RygelHTTPByteSeek;
typedef struct _RygelHTTPByteSeekClass RygelHTTPByteSeekClass;
typedef struct _RygelHTTPByteSeekPrivate RygelHTTPByteSeekPrivate;

#define RYGEL_TYPE_HTTP_REQUEST (rygel_http_request_get_type ())
#define RYGEL_HTTP_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_REQUEST, RygelHTTPRequest))
#define RYGEL_HTTP_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_REQUEST, RygelHTTPRequestClass))
#define RYGEL_IS_HTTP_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_REQUEST))
#define RYGEL_IS_HTTP_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_REQUEST))
#define RYGEL_HTTP_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_REQUEST, RygelHTTPRequestClass))

typedef struct _RygelHTTPRequest RygelHTTPRequest;
typedef struct _RygelHTTPRequestClass RygelHTTPRequestClass;

#define RYGEL_TYPE_HTTP_GET (rygel_http_get_get_type ())
#define RYGEL_HTTP_GET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_GET, RygelHTTPGet))
#define RYGEL_HTTP_GET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_GET, RygelHTTPGetClass))
#define RYGEL_IS_HTTP_GET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_GET))
#define RYGEL_IS_HTTP_GET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_GET))
#define RYGEL_HTTP_GET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_GET, RygelHTTPGetClass))

typedef struct _RygelHTTPGet RygelHTTPGet;
typedef struct _RygelHTTPGetClass RygelHTTPGetClass;
typedef struct _RygelHTTPRequestPrivate RygelHTTPRequestPrivate;

#define RYGEL_TYPE_TRANSCODE_MANAGER (rygel_transcode_manager_get_type ())
#define RYGEL_TRANSCODE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_TRANSCODE_MANAGER, RygelTranscodeManager))
#define RYGEL_TRANSCODE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_TRANSCODE_MANAGER, RygelTranscodeManagerClass))
#define RYGEL_IS_TRANSCODE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_TRANSCODE_MANAGER))
#define RYGEL_IS_TRANSCODE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_TRANSCODE_MANAGER))
#define RYGEL_TRANSCODE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_TRANSCODE_MANAGER, RygelTranscodeManagerClass))

typedef struct _RygelTranscodeManager RygelTranscodeManager;
typedef struct _RygelTranscodeManagerClass RygelTranscodeManagerClass;

#define RYGEL_TYPE_HTTP_SERVER (rygel_http_server_get_type ())
#define RYGEL_HTTP_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_SERVER, RygelHTTPServer))
#define RYGEL_HTTP_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_SERVER, RygelHTTPServerClass))
#define RYGEL_IS_HTTP_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_SERVER))
#define RYGEL_IS_HTTP_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_SERVER))
#define RYGEL_HTTP_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_SERVER, RygelHTTPServerClass))

typedef struct _RygelHTTPServer RygelHTTPServer;
typedef struct _RygelHTTPServerClass RygelHTTPServerClass;

#define RYGEL_TYPE_HTTP_ITEM_URI (rygel_http_item_uri_get_type ())
#define RYGEL_HTTP_ITEM_URI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_ITEM_URI, RygelHTTPItemURI))
#define RYGEL_HTTP_ITEM_URI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_ITEM_URI, RygelHTTPItemURIClass))
#define RYGEL_IS_HTTP_ITEM_URI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_ITEM_URI))
#define RYGEL_IS_HTTP_ITEM_URI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_ITEM_URI))
#define RYGEL_HTTP_ITEM_URI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_ITEM_URI, RygelHTTPItemURIClass))

typedef struct _RygelHTTPItemURI RygelHTTPItemURI;
typedef struct _RygelHTTPItemURIClass RygelHTTPItemURIClass;

#define RYGEL_TYPE_MEDIA_OBJECT (rygel_media_object_get_type ())
#define RYGEL_MEDIA_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_OBJECT, RygelMediaObject))
#define RYGEL_MEDIA_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_OBJECT, RygelMediaObjectClass))
#define RYGEL_IS_MEDIA_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_OBJECT))
#define RYGEL_IS_MEDIA_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_OBJECT))
#define RYGEL_MEDIA_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_OBJECT, RygelMediaObjectClass))

typedef struct _RygelMediaObject RygelMediaObject;
typedef struct _RygelMediaObjectClass RygelMediaObjectClass;

#define RYGEL_TYPE_CLIENT_HACKS (rygel_client_hacks_get_type ())
#define RYGEL_CLIENT_HACKS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_CLIENT_HACKS, RygelClientHacks))
#define RYGEL_CLIENT_HACKS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_CLIENT_HACKS, RygelClientHacksClass))
#define RYGEL_IS_CLIENT_HACKS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_CLIENT_HACKS))
#define RYGEL_IS_CLIENT_HACKS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_CLIENT_HACKS))
#define RYGEL_CLIENT_HACKS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_CLIENT_HACKS, RygelClientHacksClass))

typedef struct _RygelClientHacks RygelClientHacks;
typedef struct _RygelClientHacksClass RygelClientHacksClass;
typedef struct _RygelHTTPGetPrivate RygelHTTPGetPrivate;

#define RYGEL_TYPE_THUMBNAIL (rygel_thumbnail_get_type ())
#define RYGEL_THUMBNAIL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_THUMBNAIL, RygelThumbnail))
#define RYGEL_THUMBNAIL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_THUMBNAIL, RygelThumbnailClass))
#define RYGEL_IS_THUMBNAIL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_THUMBNAIL))
#define RYGEL_IS_THUMBNAIL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_THUMBNAIL))
#define RYGEL_THUMBNAIL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_THUMBNAIL, RygelThumbnailClass))

typedef struct _RygelThumbnail RygelThumbnail;
typedef struct _RygelThumbnailClass RygelThumbnailClass;

#define RYGEL_TYPE_SUBTITLE (rygel_subtitle_get_type ())
#define RYGEL_SUBTITLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_SUBTITLE, RygelSubtitle))
#define RYGEL_SUBTITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_SUBTITLE, RygelSubtitleClass))
#define RYGEL_IS_SUBTITLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_SUBTITLE))
#define RYGEL_IS_SUBTITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_SUBTITLE))
#define RYGEL_SUBTITLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_SUBTITLE, RygelSubtitleClass))

typedef struct _RygelSubtitle RygelSubtitle;
typedef struct _RygelSubtitleClass RygelSubtitleClass;

#define RYGEL_TYPE_HTTP_GET_HANDLER (rygel_http_get_handler_get_type ())
#define RYGEL_HTTP_GET_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_GET_HANDLER, RygelHTTPGetHandler))
#define RYGEL_HTTP_GET_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_GET_HANDLER, RygelHTTPGetHandlerClass))
#define RYGEL_IS_HTTP_GET_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_GET_HANDLER))
#define RYGEL_IS_HTTP_GET_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_GET_HANDLER))
#define RYGEL_HTTP_GET_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_GET_HANDLER, RygelHTTPGetHandlerClass))

typedef struct _RygelHTTPGetHandler RygelHTTPGetHandler;
typedef struct _RygelHTTPGetHandlerClass RygelHTTPGetHandlerClass;
typedef struct _RygelSubtitlePrivate RygelSubtitlePrivate;

#define RYGEL_TYPE_MEDIA_ITEM (rygel_media_item_get_type ())
#define RYGEL_MEDIA_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_ITEM, RygelMediaItem))
#define RYGEL_MEDIA_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_ITEM, RygelMediaItemClass))
#define RYGEL_IS_MEDIA_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_ITEM))
#define RYGEL_IS_MEDIA_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_ITEM))
#define RYGEL_MEDIA_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_ITEM, RygelMediaItemClass))

typedef struct _RygelMediaItem RygelMediaItem;
typedef struct _RygelMediaItemClass RygelMediaItemClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define RYGEL_TYPE_HTTP_SEEK_TYPE (rygel_http_seek_type_get_type ())
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define RYGEL_TYPE_MEDIA_CONTAINER (rygel_media_container_get_type ())
#define RYGEL_MEDIA_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_CONTAINER, RygelMediaContainer))
#define RYGEL_MEDIA_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_CONTAINER, RygelMediaContainerClass))
#define RYGEL_IS_MEDIA_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_CONTAINER))
#define RYGEL_IS_MEDIA_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_CONTAINER))
#define RYGEL_MEDIA_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_CONTAINER, RygelMediaContainerClass))

typedef struct _RygelMediaContainer RygelMediaContainer;
typedef struct _RygelMediaContainerClass RygelMediaContainerClass;

#define RYGEL_TYPE_HTTP_IDENTITY_HANDLER (rygel_http_identity_handler_get_type ())
#define RYGEL_HTTP_IDENTITY_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_IDENTITY_HANDLER, RygelHTTPIdentityHandler))
#define RYGEL_HTTP_IDENTITY_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_IDENTITY_HANDLER, RygelHTTPIdentityHandlerClass))
#define RYGEL_IS_HTTP_IDENTITY_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_IDENTITY_HANDLER))
#define RYGEL_IS_HTTP_IDENTITY_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_IDENTITY_HANDLER))
#define RYGEL_HTTP_IDENTITY_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_IDENTITY_HANDLER, RygelHTTPIdentityHandlerClass))

typedef struct _RygelHTTPIdentityHandler RygelHTTPIdentityHandler;
typedef struct _RygelHTTPIdentityHandlerClass RygelHTTPIdentityHandlerClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _RygelHTTPSeek {
	GObject parent_instance;
	RygelHTTPSeekPrivate * priv;
};

struct _RygelHTTPSeekClass {
	GObjectClass parent_class;
	void (*add_response_headers) (RygelHTTPSeek* self);
};

struct _RygelHTTPByteSeek {
	RygelHTTPSeek parent_instance;
	RygelHTTPByteSeekPrivate * priv;
};

struct _RygelHTTPByteSeekClass {
	RygelHTTPSeekClass parent_class;
};

typedef enum  {
	RYGEL_HTTP_SEEK_ERROR_INVALID_RANGE = SOUP_STATUS_BAD_REQUEST,
	RYGEL_HTTP_SEEK_ERROR_OUT_OF_RANGE = SOUP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE
} RygelHTTPSeekError;
#define RYGEL_HTTP_SEEK_ERROR rygel_http_seek_error_quark ()
struct _RygelHTTPRequest {
	GObject parent_instance;
	RygelHTTPRequestPrivate * priv;
	RygelHTTPServer* http_server;
	SoupServer* server;
	SoupMessage* msg;
	RygelHTTPItemURI* uri;
	RygelMediaObject* object;
	RygelClientHacks* hack;
};

struct _RygelHTTPRequestClass {
	GObjectClass parent_class;
	void (*handle) (RygelHTTPRequest* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*handle_finish) (RygelHTTPRequest* self, GAsyncResult* _res_, GError** error);
	void (*find_item) (RygelHTTPRequest* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*find_item_finish) (RygelHTTPRequest* self, GAsyncResult* _res_, GError** error);
};

struct _RygelHTTPGet {
	RygelHTTPRequest parent_instance;
	RygelHTTPGetPrivate * priv;
	RygelThumbnail* thumbnail;
	RygelSubtitle* subtitle;
	RygelHTTPSeek* seek;
	RygelHTTPGetHandler* handler;
};

struct _RygelHTTPGetClass {
	RygelHTTPRequestClass parent_class;
};

struct _RygelSubtitle {
	GTypeInstance parent_instance;
	volatile int ref_count;
	RygelSubtitlePrivate * priv;
	gchar* uri;
	gchar* mime_type;
	gchar* caption_type;
	gint64 size;
};

struct _RygelSubtitleClass {
	GTypeClass parent_class;
	void (*finalize) (RygelSubtitle *self);
};

typedef enum  {
	RYGEL_HTTP_SEEK_TYPE_BYTE,
	RYGEL_HTTP_SEEK_TYPE_TIME
} RygelHTTPSeekType;

typedef enum  {
	RYGEL_CLIENT_HACKS_ERROR_NA
} RygelClientHacksError;
#define RYGEL_CLIENT_HACKS_ERROR rygel_client_hacks_error_quark ()

static gpointer rygel_http_byte_seek_parent_class = NULL;

GType rygel_http_seek_get_type (void) G_GNUC_CONST;
GType rygel_http_byte_seek_get_type (void) G_GNUC_CONST;
enum  {
	RYGEL_HTTP_BYTE_SEEK_DUMMY_PROPERTY
};
GType rygel_http_request_get_type (void) G_GNUC_CONST;
GType rygel_http_get_get_type (void) G_GNUC_CONST;
GQuark rygel_http_seek_error_quark (void);
RygelHTTPByteSeek* rygel_http_byte_seek_new (RygelHTTPGet* request, GError** error);
RygelHTTPByteSeek* rygel_http_byte_seek_construct (GType object_type, RygelHTTPGet* request, GError** error);
GType rygel_transcode_manager_get_type (void) G_GNUC_CONST;
GType rygel_http_server_get_type (void) G_GNUC_CONST;
GType rygel_http_item_uri_get_type (void) G_GNUC_CONST;
GType rygel_media_object_get_type (void) G_GNUC_CONST;
GType rygel_client_hacks_get_type (void) G_GNUC_CONST;
GType rygel_thumbnail_get_type (void) G_GNUC_CONST;
gpointer rygel_subtitle_ref (gpointer instance);
void rygel_subtitle_unref (gpointer instance);
GParamSpec* rygel_param_spec_subtitle (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rygel_value_set_subtitle (GValue* value, gpointer v_object);
void rygel_value_take_subtitle (GValue* value, gpointer v_object);
gpointer rygel_value_get_subtitle (const GValue* value);
GType rygel_subtitle_get_type (void) G_GNUC_CONST;
GType rygel_http_get_handler_get_type (void) G_GNUC_CONST;
GType rygel_media_item_get_type (void) G_GNUC_CONST;
gint64 rygel_media_item_get_size (RygelMediaItem* self);
RygelHTTPSeek* rygel_http_seek_construct (GType object_type, SoupMessage* msg, gint64 start, gint64 stop, gint64 step, gint64 total_length, GError** error);
GType rygel_http_seek_type_get_type (void) G_GNUC_CONST;
void rygel_http_seek_set_seek_type (RygelHTTPSeek* self, RygelHTTPSeekType value);
gboolean rygel_http_byte_seek_needed (RygelHTTPGet* request);
GQuark rygel_client_hacks_error_quark (void);
RygelClientHacks* rygel_client_hacks_create (SoupMessage* message, GError** error);
gboolean rygel_client_hacks_force_seek (RygelClientHacks* self);
GType rygel_media_container_get_type (void) G_GNUC_CONST;
GType rygel_http_identity_handler_get_type (void) G_GNUC_CONST;
gboolean rygel_http_byte_seek_requested (RygelHTTPGet* request);
static void rygel_http_byte_seek_real_add_response_headers (RygelHTTPSeek* base);
SoupMessage* rygel_http_seek_get_msg (RygelHTTPSeek* self);
gint64 rygel_http_seek_get_start (RygelHTTPSeek* self);
gint64 rygel_http_seek_get_stop (RygelHTTPSeek* self);
gint64 rygel_http_seek_get_total_length (RygelHTTPSeek* self);
gint64 rygel_http_seek_get_length (RygelHTTPSeek* self);


RygelHTTPByteSeek* rygel_http_byte_seek_construct (GType object_type, RygelHTTPGet* request, GError** error) {
	RygelHTTPByteSeek * self = NULL;
	SoupRange* ranges = NULL;
	gint ranges_length1 = 0;
	gint _ranges_size_ = 0;
	gint64 start = 0LL;
	gint64 total_length = 0LL;
	const gchar* range = NULL;
	RygelHTTPGet* _tmp0_ = NULL;
	SoupMessage* _tmp1_ = NULL;
	SoupMessageHeaders* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	RygelHTTPGet* _tmp4_ = NULL;
	RygelThumbnail* _tmp5_ = NULL;
	gint64 stop = 0LL;
	gint64 _tmp18_ = 0LL;
	const gchar* _tmp19_ = NULL;
	RygelHTTPGet* _tmp41_ = NULL;
	SoupMessage* _tmp42_ = NULL;
	gint64 _tmp43_ = 0LL;
	gint64 _tmp44_ = 0LL;
	gint64 _tmp45_ = 0LL;
	GError * _inner_error_ = NULL;
#line 27 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	g_return_val_if_fail (request != NULL, NULL);
#line 29 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	start = (gint64) 0;
#line 30 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp0_ = request;
#line 30 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp1_ = ((RygelHTTPRequest*) _tmp0_)->msg;
#line 30 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp2_ = _tmp1_->request_headers;
#line 30 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp3_ = soup_message_headers_get_one (_tmp2_, "Range");
#line 30 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	range = _tmp3_;
#line 32 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp4_ = request;
#line 32 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp5_ = _tmp4_->thumbnail;
#line 32 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	if (_tmp5_ != NULL) {
#line 370 "rygel-http-byte-seek.c"
		RygelHTTPGet* _tmp6_ = NULL;
		RygelThumbnail* _tmp7_ = NULL;
		gint64 _tmp8_ = 0LL;
#line 33 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp6_ = request;
#line 33 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp7_ = _tmp6_->thumbnail;
#line 33 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp8_ = ((RygelIconInfo*) _tmp7_)->size;
#line 33 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		total_length = _tmp8_;
#line 382 "rygel-http-byte-seek.c"
	} else {
		RygelHTTPGet* _tmp9_ = NULL;
		RygelSubtitle* _tmp10_ = NULL;
#line 34 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp9_ = request;
#line 34 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp10_ = _tmp9_->subtitle;
#line 34 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		if (_tmp10_ != NULL) {
#line 392 "rygel-http-byte-seek.c"
			RygelHTTPGet* _tmp11_ = NULL;
			RygelSubtitle* _tmp12_ = NULL;
			gint64 _tmp13_ = 0LL;
#line 35 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp11_ = request;
#line 35 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp12_ = _tmp11_->subtitle;
#line 35 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp13_ = _tmp12_->size;
#line 35 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			total_length = _tmp13_;
#line 404 "rygel-http-byte-seek.c"
		} else {
			RygelHTTPGet* _tmp14_ = NULL;
			RygelMediaObject* _tmp15_ = NULL;
			gint64 _tmp16_ = 0LL;
			gint64 _tmp17_ = 0LL;
#line 37 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp14_ = request;
#line 37 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp15_ = ((RygelHTTPRequest*) _tmp14_)->object;
#line 37 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp16_ = rygel_media_item_get_size (G_TYPE_CHECK_INSTANCE_TYPE (_tmp15_, RYGEL_TYPE_MEDIA_ITEM) ? ((RygelMediaItem*) _tmp15_) : NULL);
#line 37 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp17_ = _tmp16_;
#line 37 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			total_length = _tmp17_;
#line 420 "rygel-http-byte-seek.c"
		}
	}
#line 39 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp18_ = total_length;
#line 39 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	stop = _tmp18_ - 1;
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp19_ = range;
#line 41 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	if (_tmp19_ != NULL) {
#line 431 "rygel-http-byte-seek.c"
		RygelHTTPGet* _tmp20_ = NULL;
		SoupMessage* _tmp21_ = NULL;
		SoupMessageHeaders* _tmp22_ = NULL;
		gint64 _tmp23_ = 0LL;
		SoupRange* _tmp24_ = NULL;
		gint _tmp25_ = 0;
		gboolean _tmp26_ = FALSE;
		gint64 _tmp36_ = 0LL;
		gint64 _tmp37_ = 0LL;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp20_ = request;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp21_ = ((RygelHTTPRequest*) _tmp20_)->msg;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp22_ = _tmp21_->request_headers;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp23_ = total_length;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp26_ = soup_message_headers_get_ranges (_tmp22_, _tmp23_, (SoupRange**) (&_tmp24_), &_tmp25_);
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		ranges = (g_free (ranges), NULL);
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		ranges = _tmp24_;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		ranges_length1 = _tmp25_;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_ranges_size_ = ranges_length1;
#line 42 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		if (_tmp26_) {
#line 461 "rygel-http-byte-seek.c"
			SoupRange* _tmp27_ = NULL;
			gint _tmp27__length1 = 0;
			SoupRange _tmp28_ = {0};
			gint64 _tmp29_ = 0LL;
			SoupRange* _tmp30_ = NULL;
			gint _tmp30__length1 = 0;
			SoupRange _tmp31_ = {0};
			gint64 _tmp32_ = 0LL;
#line 45 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp27_ = ranges;
#line 45 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp27__length1 = ranges_length1;
#line 45 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp28_ = _tmp27_[0];
#line 45 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp29_ = _tmp28_.start;
#line 45 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			start = _tmp29_;
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp30_ = ranges;
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp30__length1 = ranges_length1;
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp31_ = _tmp30_[0];
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp32_ = _tmp31_.end;
#line 46 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			stop = _tmp32_;
#line 490 "rygel-http-byte-seek.c"
		} else {
			const gchar* _tmp33_ = NULL;
			const gchar* _tmp34_ = NULL;
			GError* _tmp35_ = NULL;
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp33_ = _ ("Invalid Range '%s'");
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp34_ = range;
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp35_ = g_error_new (RYGEL_HTTP_SEEK_ERROR, RYGEL_HTTP_SEEK_ERROR_INVALID_RANGE, _tmp33_, _tmp34_);
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_inner_error_ = _tmp35_;
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			if (_inner_error_->domain == RYGEL_HTTP_SEEK_ERROR) {
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				g_propagate_error (error, _inner_error_);
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				ranges = (g_free (ranges), NULL);
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_g_object_unref0 (self);
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				return NULL;
#line 513 "rygel-http-byte-seek.c"
			} else {
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				ranges = (g_free (ranges), NULL);
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				g_clear_error (&_inner_error_);
#line 49 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				return NULL;
#line 523 "rygel-http-byte-seek.c"
			}
		}
#line 53 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp36_ = start;
#line 53 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp37_ = stop;
#line 53 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		if (_tmp36_ > _tmp37_) {
#line 532 "rygel-http-byte-seek.c"
			const gchar* _tmp38_ = NULL;
			const gchar* _tmp39_ = NULL;
			GError* _tmp40_ = NULL;
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp38_ = _ ("Invalid Range '%s'");
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp39_ = range;
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp40_ = g_error_new (RYGEL_HTTP_SEEK_ERROR, RYGEL_HTTP_SEEK_ERROR_INVALID_RANGE, _tmp38_, _tmp39_);
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_inner_error_ = _tmp40_;
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			if (_inner_error_->domain == RYGEL_HTTP_SEEK_ERROR) {
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				g_propagate_error (error, _inner_error_);
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				ranges = (g_free (ranges), NULL);
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_g_object_unref0 (self);
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				return NULL;
#line 554 "rygel-http-byte-seek.c"
			} else {
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				ranges = (g_free (ranges), NULL);
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				g_clear_error (&_inner_error_);
#line 54 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				return NULL;
#line 564 "rygel-http-byte-seek.c"
			}
		}
	}
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp41_ = request;
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp42_ = ((RygelHTTPRequest*) _tmp41_)->msg;
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp43_ = start;
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp44_ = stop;
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp45_ = total_length;
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	self = (RygelHTTPByteSeek*) rygel_http_seek_construct (object_type, _tmp42_, _tmp43_, _tmp44_, (gint64) 1, _tmp45_, &_inner_error_);
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	if (_inner_error_ != NULL) {
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		if (_inner_error_->domain == RYGEL_HTTP_SEEK_ERROR) {
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			g_propagate_error (error, _inner_error_);
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			ranges = (g_free (ranges), NULL);
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_g_object_unref0 (self);
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			return NULL;
#line 592 "rygel-http-byte-seek.c"
		} else {
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			ranges = (g_free (ranges), NULL);
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			g_clear_error (&_inner_error_);
#line 59 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			return NULL;
#line 602 "rygel-http-byte-seek.c"
		}
	}
#line 60 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	rygel_http_seek_set_seek_type ((RygelHTTPSeek*) self, RYGEL_HTTP_SEEK_TYPE_BYTE);
#line 27 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	ranges = (g_free (ranges), NULL);
#line 27 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	return self;
#line 611 "rygel-http-byte-seek.c"
}


RygelHTTPByteSeek* rygel_http_byte_seek_new (RygelHTTPGet* request, GError** error) {
#line 27 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	return rygel_http_byte_seek_construct (RYGEL_TYPE_HTTP_BYTE_SEEK, request, error);
#line 618 "rygel-http-byte-seek.c"
}


gboolean rygel_http_byte_seek_needed (RygelHTTPGet* request) {
	gboolean result = FALSE;
	gboolean force_seek = FALSE;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp36_ = FALSE;
	GError * _inner_error_ = NULL;
#line 63 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	g_return_val_if_fail (request != NULL, FALSE);
#line 64 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	force_seek = FALSE;
#line 633 "rygel-http-byte-seek.c"
	{
		RygelClientHacks* hack = NULL;
		RygelHTTPGet* _tmp0_ = NULL;
		SoupMessage* _tmp1_ = NULL;
		RygelClientHacks* _tmp2_ = NULL;
		gboolean _tmp3_ = FALSE;
#line 67 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp0_ = request;
#line 67 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp1_ = ((RygelHTTPRequest*) _tmp0_)->msg;
#line 67 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp2_ = rygel_client_hacks_create (_tmp1_, &_inner_error_);
#line 67 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		hack = _tmp2_;
#line 67 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		if (_inner_error_ != NULL) {
#line 650 "rygel-http-byte-seek.c"
			goto __catch28_g_error;
		}
#line 68 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp3_ = rygel_client_hacks_force_seek (hack);
#line 68 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		force_seek = _tmp3_;
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_object_unref0 (hack);
#line 659 "rygel-http-byte-seek.c"
	}
	goto __finally28;
	__catch28_g_error:
	{
		GError* _error_ = NULL;
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_error_ = _inner_error_;
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_inner_error_ = NULL;
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_error_free0 (_error_);
#line 671 "rygel-http-byte-seek.c"
	}
	__finally28:
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	if (_inner_error_ != NULL) {
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		g_clear_error (&_inner_error_);
#line 66 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		return FALSE;
#line 682 "rygel-http-byte-seek.c"
	}
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp5_ = force_seek;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	if (_tmp5_) {
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp4_ = TRUE;
#line 690 "rygel-http-byte-seek.c"
	} else {
		gboolean _tmp6_ = FALSE;
		gboolean _tmp7_ = FALSE;
		gboolean _tmp8_ = FALSE;
		RygelHTTPGet* _tmp9_ = NULL;
		RygelMediaObject* _tmp10_ = NULL;
		gboolean _tmp19_ = FALSE;
		gboolean _tmp27_ = FALSE;
		gboolean _tmp35_ = FALSE;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp9_ = request;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp10_ = ((RygelHTTPRequest*) _tmp9_)->object;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		if (!G_TYPE_CHECK_INSTANCE_TYPE (_tmp10_, RYGEL_TYPE_MEDIA_CONTAINER)) {
#line 706 "rygel-http-byte-seek.c"
			gboolean _tmp11_ = FALSE;
			RygelHTTPGet* _tmp12_ = NULL;
			RygelMediaObject* _tmp13_ = NULL;
			gint64 _tmp14_ = 0LL;
			gint64 _tmp15_ = 0LL;
			gboolean _tmp18_ = FALSE;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp12_ = request;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp13_ = ((RygelHTTPRequest*) _tmp12_)->object;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp14_ = rygel_media_item_get_size (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, RYGEL_TYPE_MEDIA_ITEM) ? ((RygelMediaItem*) _tmp13_) : NULL);
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp15_ = _tmp14_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			if (_tmp15_ > ((gint64) 0)) {
#line 723 "rygel-http-byte-seek.c"
				RygelHTTPGet* _tmp16_ = NULL;
				RygelHTTPGetHandler* _tmp17_ = NULL;
#line 72 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp16_ = request;
#line 72 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp17_ = _tmp16_->handler;
#line 72 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp11_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp17_, RYGEL_TYPE_HTTP_IDENTITY_HANDLER);
#line 732 "rygel-http-byte-seek.c"
			} else {
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp11_ = FALSE;
#line 736 "rygel-http-byte-seek.c"
			}
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp18_ = _tmp11_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp8_ = _tmp18_;
#line 742 "rygel-http-byte-seek.c"
		} else {
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp8_ = FALSE;
#line 746 "rygel-http-byte-seek.c"
		}
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp19_ = _tmp8_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		if (_tmp19_) {
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp7_ = TRUE;
#line 754 "rygel-http-byte-seek.c"
		} else {
			gboolean _tmp20_ = FALSE;
			RygelHTTPGet* _tmp21_ = NULL;
			RygelThumbnail* _tmp22_ = NULL;
			gboolean _tmp26_ = FALSE;
#line 73 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp21_ = request;
#line 73 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp22_ = _tmp21_->thumbnail;
#line 73 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			if (_tmp22_ != NULL) {
#line 766 "rygel-http-byte-seek.c"
				RygelHTTPGet* _tmp23_ = NULL;
				RygelThumbnail* _tmp24_ = NULL;
				gint64 _tmp25_ = 0LL;
#line 74 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp23_ = request;
#line 74 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp24_ = _tmp23_->thumbnail;
#line 74 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp25_ = ((RygelIconInfo*) _tmp24_)->size;
#line 74 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp20_ = _tmp25_ > ((gint64) 0);
#line 778 "rygel-http-byte-seek.c"
			} else {
#line 73 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp20_ = FALSE;
#line 782 "rygel-http-byte-seek.c"
			}
#line 73 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp26_ = _tmp20_;
#line 73 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp7_ = _tmp26_;
#line 788 "rygel-http-byte-seek.c"
		}
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp27_ = _tmp7_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		if (_tmp27_) {
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp6_ = TRUE;
#line 796 "rygel-http-byte-seek.c"
		} else {
			gboolean _tmp28_ = FALSE;
			RygelHTTPGet* _tmp29_ = NULL;
			RygelSubtitle* _tmp30_ = NULL;
			gboolean _tmp34_ = FALSE;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp29_ = request;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp30_ = _tmp29_->subtitle;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			if (_tmp30_ != NULL) {
#line 808 "rygel-http-byte-seek.c"
				RygelHTTPGet* _tmp31_ = NULL;
				RygelSubtitle* _tmp32_ = NULL;
				gint64 _tmp33_ = 0LL;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp31_ = request;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp32_ = _tmp31_->subtitle;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp33_ = _tmp32_->size;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp28_ = _tmp33_ > ((gint64) 0);
#line 820 "rygel-http-byte-seek.c"
			} else {
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
				_tmp28_ = FALSE;
#line 824 "rygel-http-byte-seek.c"
			}
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp34_ = _tmp28_;
#line 75 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
			_tmp6_ = _tmp34_;
#line 830 "rygel-http-byte-seek.c"
		}
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp35_ = _tmp6_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp4_ = _tmp35_;
#line 836 "rygel-http-byte-seek.c"
	}
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp36_ = _tmp4_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	result = _tmp36_;
#line 71 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	return result;
#line 844 "rygel-http-byte-seek.c"
}


gboolean rygel_http_byte_seek_requested (RygelHTTPGet* request) {
	gboolean result = FALSE;
	RygelHTTPGet* _tmp0_ = NULL;
	SoupMessage* _tmp1_ = NULL;
	SoupMessageHeaders* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 78 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	g_return_val_if_fail (request != NULL, FALSE);
#line 79 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp0_ = request;
#line 79 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp1_ = ((RygelHTTPRequest*) _tmp0_)->msg;
#line 79 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp2_ = _tmp1_->request_headers;
#line 79 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp3_ = soup_message_headers_get_one (_tmp2_, "Range");
#line 79 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	result = _tmp3_ != NULL;
#line 79 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	return result;
#line 868 "rygel-http-byte-seek.c"
}


static void rygel_http_byte_seek_real_add_response_headers (RygelHTTPSeek* base) {
	RygelHTTPByteSeek * self;
	gchar* range = NULL;
	gchar* _tmp0_ = NULL;
	SoupMessageHeaders* headers = NULL;
	SoupMessage* _tmp1_ = NULL;
	SoupMessage* _tmp2_ = NULL;
	SoupMessageHeaders* _tmp3_ = NULL;
	SoupMessage* _tmp4_ = NULL;
	SoupMessage* _tmp5_ = NULL;
	SoupMessageHeaders* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	SoupMessageHeaders* _tmp33_ = NULL;
	gint64 _tmp34_ = 0LL;
	gint64 _tmp35_ = 0LL;
#line 82 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	self = (RygelHTTPByteSeek*) base;
#line 84 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp0_ = g_strdup ("bytes ");
#line 84 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	range = _tmp0_;
#line 85 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp1_ = rygel_http_seek_get_msg ((RygelHTTPSeek*) self);
#line 85 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp2_ = _tmp1_;
#line 85 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp3_ = _tmp2_->response_headers;
#line 85 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	headers = _tmp3_;
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp4_ = rygel_http_seek_get_msg ((RygelHTTPSeek*) self);
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp5_ = _tmp4_;
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp6_ = _tmp5_->request_headers;
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp7_ = soup_message_headers_get_one (_tmp6_, "Range");
#line 87 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	if (_tmp7_ != NULL) {
#line 911 "rygel-http-byte-seek.c"
		SoupMessageHeaders* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gint64 _tmp10_ = 0LL;
		gint64 _tmp11_ = 0LL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		gint64 _tmp16_ = 0LL;
		gint64 _tmp17_ = 0LL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		gint64 _tmp24_ = 0LL;
		gint64 _tmp25_ = 0LL;
		gchar* _tmp26_ = NULL;
		gchar* _tmp27_ = NULL;
		gchar* _tmp28_ = NULL;
		gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		SoupMessageHeaders* _tmp31_ = NULL;
		const gchar* _tmp32_ = NULL;
#line 88 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp8_ = headers;
#line 88 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		soup_message_headers_append (_tmp8_, "Accept-Ranges", "bytes");
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp9_ = range;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp10_ = rygel_http_seek_get_start ((RygelHTTPSeek*) self);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp11_ = _tmp10_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp12_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp11_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp13_ = _tmp12_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp14_ = g_strconcat (_tmp13_, "-", NULL);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp15_ = _tmp14_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp16_ = rygel_http_seek_get_stop ((RygelHTTPSeek*) self);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp17_ = _tmp16_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp18_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp17_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp19_ = _tmp18_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp20_ = g_strconcat (_tmp15_, _tmp19_, NULL);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp21_ = _tmp20_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp22_ = g_strconcat (_tmp21_, "/", NULL);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp23_ = _tmp22_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp24_ = rygel_http_seek_get_total_length ((RygelHTTPSeek*) self);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp25_ = _tmp24_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp26_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp25_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp27_ = _tmp26_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp28_ = g_strconcat (_tmp23_, _tmp27_, NULL);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp29_ = _tmp28_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp30_ = g_strconcat (_tmp9_, _tmp29_, NULL);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_free0 (range);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		range = _tmp30_;
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_free0 (_tmp29_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_free0 (_tmp27_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_free0 (_tmp23_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_free0 (_tmp21_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_free0 (_tmp19_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_free0 (_tmp15_);
#line 90 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_g_free0 (_tmp13_);
#line 93 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp31_ = headers;
#line 93 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		_tmp32_ = range;
#line 93 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
		soup_message_headers_append (_tmp31_, "Content-Range", _tmp32_);
#line 1009 "rygel-http-byte-seek.c"
	}
#line 96 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp33_ = headers;
#line 96 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp34_ = rygel_http_seek_get_length ((RygelHTTPSeek*) self);
#line 96 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_tmp35_ = _tmp34_;
#line 96 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	soup_message_headers_set_content_length (_tmp33_, _tmp35_);
#line 82 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	_g_free0 (range);
#line 1021 "rygel-http-byte-seek.c"
}


static void rygel_http_byte_seek_class_init (RygelHTTPByteSeekClass * klass) {
#line 26 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	rygel_http_byte_seek_parent_class = g_type_class_peek_parent (klass);
#line 26 "/home/jku/src/jhbuild/sources/rygel/src/librygel-server/rygel-http-byte-seek.vala"
	RYGEL_HTTP_SEEK_CLASS (klass)->add_response_headers = rygel_http_byte_seek_real_add_response_headers;
#line 1030 "rygel-http-byte-seek.c"
}


static void rygel_http_byte_seek_instance_init (RygelHTTPByteSeek * self) {
}


GType rygel_http_byte_seek_get_type (void) {
	static volatile gsize rygel_http_byte_seek_type_id__volatile = 0;
	if (g_once_init_enter (&rygel_http_byte_seek_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RygelHTTPByteSeekClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rygel_http_byte_seek_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RygelHTTPByteSeek), 0, (GInstanceInitFunc) rygel_http_byte_seek_instance_init, NULL };
		GType rygel_http_byte_seek_type_id;
		rygel_http_byte_seek_type_id = g_type_register_static (RYGEL_TYPE_HTTP_SEEK, "RygelHTTPByteSeek", &g_define_type_info, 0);
		g_once_init_leave (&rygel_http_byte_seek_type_id__volatile, rygel_http_byte_seek_type_id);
	}
	return rygel_http_byte_seek_type_id__volatile;
}



